name: Integration continue

on:
  push:
    branches:
      - main
      - composite-action-demo
  workflow_dispatch:


jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Build
        run: npm run build -w backend
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Build
        run: npm run build -w frontend
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Test
        run: npm run test -w backend
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Test
        run: npm run test -w frontend
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Lint
        run: npm run lint -w backend
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Lint
        run: npm run lint -w frontend
