name: Integration continue

on:
  push:
    branches:
      - main
    tags:
      - '**'

  workflow_dispatch:


jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Build
        run: npm run build -w backend
      - uses: actions/upload-artifact@v2
        with:
          name: build-backend
          path: backend/dist
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
        with:
          node-version: 18.x
          run_install: false
      - name: Build
        run: npm run build -w frontend
      - uses: actions/upload-artifact@v2
        with:
          name: build-frontend
          path: frontend/dist
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Test
        run: npm run test -w backend
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Test
        run: npm run test -w frontend
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Lint
        run: npm run lint -w backend
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installation de NodeJS / Cache / Deps
        uses: ./.github/actions/setup-node
      - name: Lint
        run: npm run lint -w frontend

  release:
    runs-on: ubuntu-latest
    needs: [build-frontend,build-backend, test-frontend, test-backend, lint-frontend, lint-backend]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        with:
          name: build-frontend
          path: frontend/dist
      - uses: actions/download-artifact@v2
        with:
          name: build-frontend
          path: backend/dist
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            frontend/dist/
            backend/dist/
